version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: teachee_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: quiz_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: teachee_webapp
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password123@db:5432/quiz_db
      - OLLAMA_URL=http://ollama:11434
      - AI_MODEL=quizzy:latest
      - OLLAMA_TIMEOUT=600
      - JWT_SECRET_KEY=d3aea72647a1f9847954e1e745e3d878c86482d4dab9d01b52a910f92243ddac

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@school.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "8080:80"
    depends_on:
      - db

  ollama:
    image: ollama/ollama
    container_name: teachee_ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./modelfiles:/modelfiles

volumes:
  pgdata:
  ollama_data:
